import { Navigation } from "@/components/landing/Navigation";
import { Footer } from "@/components/landing/Footer";
import { FileText } from "lucide-react";

const Terms = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      
      <main className="flex-1 py-20 px-4">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-3 mb-6">
            <FileText className="h-8 w-8 text-primary" />
            <h1 className="text-4xl font-bold">Let's Paliyo Together</h1>
          </div>
          
          <p className="text-muted-foreground mb-8">
            Last updated: January 2025
          </p>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-bold mb-4">Terms of Service</h2>
              <p className="text-muted-foreground leading-relaxed">
                Welcome to Paliyo! By using our services, you agree to these Terms of Service. Please read them carefully. If you don't agree, please don't use our services.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Usage Rights</h2>
              <h3 className="text-xl font-semibold mb-3">What You Can Do</h3>
              <ul className="space-y-2 text-muted-foreground">
                <li>Create child profiles and customize their Paliyo experience</li>
                <li>Access all features included in your subscription plan</li>
                <li>Download and export your data, including conversation logs and uploaded content</li>
                <li>Share generated stories within your family (not for commercial use)</li>
              </ul>

              <h3 className="text-xl font-semibold mb-3 mt-6">What You Can't Do</h3>
              <ul className="space-y-2 text-muted-foreground">
                <li>Share your account credentials or allow unauthorized access</li>
                <li>Use Paliyo for commercial purposes without written permission</li>
                <li>Attempt to reverse-engineer, hack, or compromise our systems</li>
                <li>Upload harmful, illegal, or inappropriate content</li>
                <li>Violate any applicable laws or regulations</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Subscriptions & Payments</h2>
              <h3 className="text-xl font-semibold mb-3">Billing</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                Subscription plans are billed monthly or annually based on your selection. All fees are in USD and charged to your payment method on file.
              </p>
              
              <h3 className="text-xl font-semibold mb-3">Free Trial</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                New users may be eligible for a free trial period. You won't be charged until the trial ends. Cancel anytime before the trial expires to avoid charges.
              </p>

              <h3 className="text-xl font-semibold mb-3">Cancellation & Refunds</h3>
              <ul className="space-y-2 text-muted-foreground">
                <li>Cancel your subscription anytime—no penalties</li>
                <li>You'll retain access until the end of your current billing period</li>
                <li>30-day money-back guarantee for new subscribers</li>
                <li>Refunds processed within 5-7 business days</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Content Ownership</h2>
              <h3 className="text-xl font-semibold mb-3">Your Content</h3>
              <p className="text-muted-foreground leading-relaxed mb-4">
                You retain all rights to content you upload (photos, stories, family memories). By uploading, you grant us a license to use this content solely to provide our services to you.
              </p>

              <h3 className="text-xl font-semibold mb-3">Generated Content</h3>
              <p className="text-muted-foreground leading-relaxed">
                Stories and responses generated by Paliyo are for your personal, non-commercial use. You own the output, but we retain intellectual property rights to our AI models and systems.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Service Availability</h2>
              <p className="text-muted-foreground leading-relaxed">
                We strive for 99.9% uptime but can't guarantee uninterrupted service. We may perform maintenance, updates, or modifications that temporarily affect access. We'll notify you of planned downtime when possible.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Termination</h2>
              <p className="text-muted-foreground leading-relaxed">
                We reserve the right to suspend or terminate accounts that violate these Terms, engage in fraudulent activity, or pose safety risks. You'll receive notice and opportunity to address issues when possible.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Liability Limitations</h2>
              <p className="text-muted-foreground leading-relaxed">
                Paliyo is provided "as is" for educational and entertainment purposes. While we implement extensive safety measures, parents remain responsible for supervising their children's use. We are not liable for indirect, incidental, or consequential damages arising from service use.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Changes to Terms</h2>
              <p className="text-muted-foreground leading-relaxed">
                We may update these Terms periodically. Material changes will be communicated via email or in-app notification. Continued use after changes constitutes acceptance.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold mb-4">Contact & Disputes</h2>
              <p className="text-muted-foreground leading-relaxed">
                Questions or concerns? Contact us at <a href="mailto:legal@paliyo.com" className="text-primary hover:underline">legal@paliyo.com</a>. For disputes, we encourage informal resolution first. These Terms are governed by the laws of [Jurisdiction].
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Terms;
